const USER_SIGNED_IN = 'USER_SIGNED_IN';
const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
const REGISTER_BUSINESS = 'REGISTER_BUSINESS';

export {
  USER_SIGNED_IN,
  REGISTER_BUSINESS,
  USER_LOGGED_OUT
};
