const USER_SIGNED_IN = 'USER_SIGNED_IN';
const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
const REGISTER_BUSINESS = 'REGISTER_BUSINESS';
const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
const GET_BUSINESS_DETAILS = 'GET_BUSINESS_DETAILS';
const GET_ALL_BUSINESSES = 'GET_ALL_BUSINESSES';
const EDIT_BUSINESS = 'EDIT_BUSINESS';
const CHANGE_OWNERSHIP = 'CHANGE_OWNERSHIP';
const DELETE_BUSINESS = 'DELETE_BUSINESS';
const ADD_REVIEW = 'ADD_REVIEW';
const GET_BUSINESS_REVIEWS = 'GET_BUSINESS_REVIEWS';

export {
  USER_SIGNED_IN,
  USER_LOGGED_OUT,
  FETCH_USER_DETAILS,
  REGISTER_BUSINESS,
  GET_ALL_CATEGORIES,
  GET_BUSINESS_DETAILS,
  GET_ALL_BUSINESSES,
  EDIT_BUSINESS,
  CHANGE_OWNERSHIP,
  DELETE_BUSINESS,
  ADD_REVIEW,
  GET_BUSINESS_REVIEWS
};
