const USER_SIGNED_IN = 'USER_SIGNED_IN';
const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
const REGISTER_BUSINESS = 'REGISTER_BUSINESS';
const REGISTER_BUSINESS_FAILED = 'REGISTER_BUSINESS_FAILED';
const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
const GET_BUSINESS_DETAILS = 'GET_BUSINESS_DETAILS';
const GET_BUSINESS_FAILED = 'GET_BUSINESS_FAILED';
const GET_ALL_BUSINESSES = 'GET_ALL_BUSINESSES';
const EDIT_BUSINESS = 'EDIT_BUSINESS';
const EDIT_BUSINESS_FAILED = 'EDIT_BUSINESS_FAILED';
const CHANGE_OWNERSHIP = 'CHANGE_OWNERSHIP';
const CHANGE_OWNERSHIP_FAILED = 'CHANGE_OWNERSHIP_FAILED';
const DELETE_BUSINESS = 'DELETE_BUSINESS';
const DELETE_BUSINESS_FAILED = 'DELETE_BUSINESS_FAILED';
const ADD_REVIEW = 'ADD_REVIEW';
const ADD_REVIEW_FAILED = 'ADD_REVIEW_FAILED';
const GET_BUSINESS_REVIEWS = 'GET_BUSINESS_REVIEWS';
const GET_REVIEW = 'GET_REVIEW';
const EDIT_REVIEW = 'EDIT_REVIEW';
const EDIT_REVIEW_FAILED = 'EDIT_REVIEW_FAILED';
const DELETE_REVIEW = 'DELETE_REVIEW';
const DELETE_REVIEW_FAILED = 'DELETE_REVIEW_FAILED';
const GET_USER_BUSINESSES = 'GET_USER_BUSINESSES';
const GET_USER_BUSINESSES_FAILED = 'GET_USER_BUSINESSES_FAILED';
const EDIT_USER_DETAIL = 'EDIT_USER_DETAIL';
const EDIT_USER_DETAIL_FAILED = 'EDIT_USER_DETAIL_FAILED';
const BUSINESS_RATING = 'BUSINESS_RATING';
const IS_PAGE_LOADING = 'IS_PAGE_LOADING';
const IS_REQUEST_LOADING = 'IS_REQUEST_LOADING';
const VERIFY_ACCOUNT = 'VERIFY_ACCOUNT';
const VERIFY_ACCOUNT_FAILED = 'VERIFY_ACCOUNT_FAILED';

export {
  USER_SIGNED_IN,
  SIGN_IN_FAILED,
  USER_LOGGED_OUT,
  FETCH_USER_DETAILS,
  REGISTER_BUSINESS,
  REGISTER_BUSINESS_FAILED,
  GET_ALL_CATEGORIES,
  GET_BUSINESS_DETAILS,
  GET_BUSINESS_FAILED,
  GET_ALL_BUSINESSES,
  EDIT_BUSINESS,
  EDIT_BUSINESS_FAILED,
  CHANGE_OWNERSHIP,
  CHANGE_OWNERSHIP_FAILED,
  DELETE_BUSINESS,
  DELETE_BUSINESS_FAILED,
  ADD_REVIEW,
  ADD_REVIEW_FAILED,
  GET_BUSINESS_REVIEWS,
  GET_REVIEW,
  EDIT_REVIEW,
  EDIT_REVIEW_FAILED,
  DELETE_REVIEW,
  DELETE_REVIEW_FAILED,
  GET_USER_BUSINESSES,
  GET_USER_BUSINESSES_FAILED,
  EDIT_USER_DETAIL,
  EDIT_USER_DETAIL_FAILED,
  BUSINESS_RATING,
  IS_PAGE_LOADING,
  IS_REQUEST_LOADING,
  VERIFY_ACCOUNT,
  VERIFY_ACCOUNT_FAILED
};
